/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerId = IDL.Nat32;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchType = IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null });
export const Time = IDL.Int;
export const MatchId = IDL.Nat32;
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'playerId' : IDL.Opt(PlayerId),
});
export const MatchStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : MatchId,
  'playerIds' : IDL.Vec(PlayerId),
  'matchType' : MatchType,
  'status' : MatchStatus,
  'title' : IDL.Text,
  'winnerId' : IDL.Opt(PlayerId),
  'prizeAmount' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'roomId' : IDL.Text,
  'scheduledAt' : Time,
});
export const Player = IDL.Record({
  'id' : PlayerId,
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'wins' : IDL.Nat,
  'referredBy' : IDL.Opt(IDL.Text),
  'totalEarnings' : IDL.Nat,
  'matchesPlayed' : IDL.Nat,
  'walletBalance' : IDL.Nat,
});
export const TxId = IDL.Nat32;
export const TxType = IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null });
export const WalletTransaction = IDL.Record({
  'id' : TxId,
  'userId' : PlayerId,
  'description' : IDL.Text,
  'timestamp' : Time,
  'txType' : TxType,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustPlayerWallet' : IDL.Func([PlayerId, IDL.Int, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func(
      [IDL.Text, MatchType, IDL.Nat, IDL.Nat, Time, IDL.Text],
      [MatchId],
      [],
    ),
  'deleteMatch' : IDL.Func([MatchId], [], []),
  'getAdminDashboard' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Opt(IDL.Nat)))],
      ['query'],
    ),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getPlayerDetails' : IDL.Func([PlayerId], [Player], ['query']),
  'getPlayerMatches' : IDL.Func([PlayerId], [IDL.Vec(Match)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletTransactions' : IDL.Func(
      [PlayerId],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinMatch' : IDL.Func([MatchId], [], []),
  'registerPlayer' : IDL.Func([IDL.Text], [PlayerId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMatchResult' : IDL.Func([MatchId, PlayerId], [], []),
  'updateMatch' : IDL.Func(
      [
        MatchId,
        IDL.Text,
        MatchType,
        IDL.Nat,
        IDL.Nat,
        Time,
        IDL.Text,
        MatchStatus,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerId = IDL.Nat32;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchType = IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null });
  const Time = IDL.Int;
  const MatchId = IDL.Nat32;
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'playerId' : IDL.Opt(PlayerId),
  });
  const MatchStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : MatchId,
    'playerIds' : IDL.Vec(PlayerId),
    'matchType' : MatchType,
    'status' : MatchStatus,
    'title' : IDL.Text,
    'winnerId' : IDL.Opt(PlayerId),
    'prizeAmount' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'roomId' : IDL.Text,
    'scheduledAt' : Time,
  });
  const Player = IDL.Record({
    'id' : PlayerId,
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'wins' : IDL.Nat,
    'referredBy' : IDL.Opt(IDL.Text),
    'totalEarnings' : IDL.Nat,
    'matchesPlayed' : IDL.Nat,
    'walletBalance' : IDL.Nat,
  });
  const TxId = IDL.Nat32;
  const TxType = IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null });
  const WalletTransaction = IDL.Record({
    'id' : TxId,
    'userId' : PlayerId,
    'description' : IDL.Text,
    'timestamp' : Time,
    'txType' : TxType,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustPlayerWallet' : IDL.Func([PlayerId, IDL.Int, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func(
        [IDL.Text, MatchType, IDL.Nat, IDL.Nat, Time, IDL.Text],
        [MatchId],
        [],
      ),
    'deleteMatch' : IDL.Func([MatchId], [], []),
    'getAdminDashboard' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Opt(IDL.Nat)))],
        ['query'],
      ),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getPlayerDetails' : IDL.Func([PlayerId], [Player], ['query']),
    'getPlayerMatches' : IDL.Func([PlayerId], [IDL.Vec(Match)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletTransactions' : IDL.Func(
        [PlayerId],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinMatch' : IDL.Func([MatchId], [], []),
    'registerPlayer' : IDL.Func([IDL.Text], [PlayerId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMatchResult' : IDL.Func([MatchId, PlayerId], [], []),
    'updateMatch' : IDL.Func(
        [
          MatchId,
          IDL.Text,
          MatchType,
          IDL.Nat,
          IDL.Nat,
          Time,
          IDL.Text,
          MatchStatus,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };