/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Match {
  'id' : MatchId,
  'playerIds' : Uint32Array,
  'matchType' : MatchType,
  'status' : MatchStatus,
  'title' : string,
  'winnerId' : [] | [PlayerId],
  'prizeAmount' : bigint,
  'entryFee' : bigint,
  'roomId' : string,
  'scheduledAt' : Time,
}
export type MatchId = number;
export type MatchStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export type MatchType = { 'free' : null } |
  { 'paid' : null };
export interface Player {
  'id' : PlayerId,
  'referralCode' : string,
  'username' : string,
  'wins' : bigint,
  'referredBy' : [] | [string],
  'totalEarnings' : bigint,
  'matchesPlayed' : bigint,
  'walletBalance' : bigint,
}
export type PlayerId = number;
export type Time = bigint;
export type TxId = number;
export type TxType = { 'credit' : null } |
  { 'debit' : null };
export interface UserProfile {
  'username' : string,
  'playerId' : [] | [PlayerId],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'id' : TxId,
  'userId' : PlayerId,
  'description' : string,
  'timestamp' : Time,
  'txType' : TxType,
  'amount' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adjustPlayerWallet' : ActorMethod<[PlayerId, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<
    [string, MatchType, bigint, bigint, Time, string],
    MatchId
  >,
  'deleteMatch' : ActorMethod<[MatchId], undefined>,
  'getAdminDashboard' : ActorMethod<[], [bigint, bigint, bigint]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<[string, [] | [bigint]]>>,
  'getMatches' : ActorMethod<[], Array<Match>>,
  'getPlayerDetails' : ActorMethod<[PlayerId], Player>,
  'getPlayerMatches' : ActorMethod<[PlayerId], Array<Match>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletTransactions' : ActorMethod<[PlayerId], Array<WalletTransaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinMatch' : ActorMethod<[MatchId], undefined>,
  'registerPlayer' : ActorMethod<[string], PlayerId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMatchResult' : ActorMethod<[MatchId, PlayerId], undefined>,
  'updateMatch' : ActorMethod<
    [MatchId, string, MatchType, bigint, bigint, Time, string, MatchStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];